### ISSUE TITLE
分享了您的可视化图

### ISSUE THREAD

**Issue by YiranJing** [Mistletoer/NCP-historical-data-visualization-2019-nCoV-#1]
您好，刚刚看到了您的可视化，感觉是我目前见过的最棒的中国可视化。而且是python实现的 ，太厉害了。（会跟进和默默学习您这个动态可视化）

顺便告知，我把您的dashboard 分享在了我的repo里。https://github.com/YiranJing/Coronavirus-Epidemic-2019-nCov

**Comment by yuanqingZou** [comment]
您好，刚刚看了您精心制作的数据可视化demo。美观的布局和清晰的数据呈现让我佩服的五体投地。

**Comment by Minghou-Lei** [comment]
谢谢您的支持
