### ISSUE TITLE
您好，请问2.16号之后及现在的数据怎样动态刷新到图表中，运行py文件吗，部署到Linux服务器呢，谢谢谢谢

### ISSUE THREAD

**Issue by CoderAceHao** [Mistletoer/NCP-historical-data-visualization-2019-nCoV-#3]
你好，请问2.16号之后及现在的数据怎样动态刷新到图表中，运行,py文件吗？没接触过Python，想借此学习一下，可以话，跟我说一下您的邮箱或者WX号来联系，谢谢啦

**Comment by Minghou-Lei** [comment]
你好，现在已修复数据不完全的问题，直接运行py脚本即可，会在当前位置生成一个HTML文件。
